const fs = require('fs');
const yaml = require('js-yaml');

const { FileType } = require('./fileType');
const { checkEmpty } = require('./helper');
const YAML = require('yamljs');

const DEFAULT_TITLE = "My Swag API";
const DEFAULT_DESCRIPTION = "This api is generated by Swag Auto.";
const DEFAULT_TYPE = FileType.JSON;
const DEFAULT_FILE_NAME = './swagger';

function autoGen(title, description, type) {
  if (checkEmpty(title)) {
    title = DEFAULT_TITLE;
  }

  if (checkEmpty(description)) {
    description = DEFAULT_DESCRIPTION;
  }

  if (checkEmpty(type)) {
    type = DEFAULT_TYPE;
  }

  const path = DEFAULT_FILE_NAME + type;
  var rawdata;

  fileGenerator(type, path);

  if (fs.existsSync(path)) {
    rawdata = fs.readFileSync(path);
  }

  if (type == FileType.JSON) {
    genJsonFile(rawdata, path, title, description);
  }

  if (type == FileType.YAML) {
    genYamlFile(rawdata, path, title, description);
  }

  return path;
}

function fileGenerator(type, path) {
  checkEmpty(type);
  checkEmpty(path);

  try {
    if (!fs.existsSync(path)) {
      var copyableFile = fs.readFileSync(__dirname + "/swag" + type);
      checkEmpty(copyableFile);

      fs.writeFileSync("swagger" + type, copyableFile, function (err) {
        if (err) {
          throw err;
        }

        console.log("Swagger" + type + " succesfully created!");
      });
    }
  } catch (err) {
    console.error(err)
  }
}

function genJsonFile(data, path, title, description) {
  try {
    let swag = JSON.parse(data);
    swag.info.title = title;
    swag.info.description = description;
    fs.writeFileSync(path, JSON.stringify(swag));

    console.log(swag);
  } catch (error) {
    console.log(error);
  }
}

function genYamlFile(data, path, title, description) {
  try {
    let fileContents = fs.readFileSync(path, 'utf8');
    let swag = yaml.safeLoad(fileContents);

    swag.info.title = title;
    swag.info.description = description;
    let yamlStr = yaml.safeDump(swag);
    fs.writeFileSync(path, yamlStr);

    return swag;

  } catch (e) {
    console.log(e);
  }
}

function swagConfig(title, description) {
  return {
    title: title,
    description: description
  }
}

function swagAuto(title, description, type) {
  if (type == FileType.JSON) {
    path = autoGen(title, description, type);

    return require("." + path);
  } else if (type == FileType.YAML) {
    autoGen(title, description, type);
    let yamlData = swaggerDocument = YAML.load(DEFAULT_FILE_NAME + type);

    return yamlData;
  }
}

module.exports = {
  autoGen,
  swagConfig,
  swagAuto,
  FileType
}